 import Link from "next/link";
import { assets } from "@/data/assets";

export default async function AssetPage({
  params,
}: {
  params: Promise<{ symbol: string }>;
}) {
  const { symbol } = await params;

  const assetKey = symbol.toLowerCase() as keyof typeof assets;
  const asset = assets[assetKey];

  if (!asset) {
    return (
      <main className="min-h-screen bg-black text-white">
        <div className="mx-auto max-w-5xl px-6 py-16">
          <h1 className="text-4xl font-bold">Asset not found</h1>

          <Link
            href="/"
            className="mt-6 inline-block text-green-400 hover:text-green-300"
          >
            ← Back to dashboard
          </Link>
        </div>
      </main>
    );
  }

  const volumePoints =
    asset.metrics.volumeMultiplier >= 4
      ? 40
      : asset.metrics.volumeMultiplier >= 2
        ? 25
        : asset.metrics.volumeMultiplier >= 1.5
          ? 10
          : 0;

  const transferPoints = asset.metrics.largeTransfer ? 30 : 0;

  const concentrationPoints =
    asset.metrics.walletConcentration >= 70
      ? 30
      : asset.metrics.walletConcentration >= 50
        ? 20
        : asset.metrics.walletConcentration >= 30
          ? 10
          : 0;

  return (
    <main className="min-h-screen bg-black text-white">
      <div className="mx-auto max-w-5xl px-6 py-16">
        <Link
          href="/"
          className="mb-8 inline-block text-sm text-gray-400 hover:text-white"
        >
          ← Back to dashboard
        </Link>

        <p className="mb-3 text-sm text-green-400">
          INVESTIGATION CASE
        </p>

        <h1 className="text-5xl font-bold">
          {asset.name}
        </h1>

        <p className="mt-3 text-gray-400">
          Tokenized Pre-IPO Asset Investigation
        </p>

        <div className="mt-10 grid gap-6 md:grid-cols-3">
          <div className="rounded-2xl border border-gray-800 bg-gray-950 p-6">
            <p className="text-sm text-gray-500">
              Risk Score
            </p>

            <p
              className={`mt-2 text-3xl font-bold ${
                asset.risk >= 80
                  ? "text-red-400"
                  : asset.risk >= 60
                    ? "text-yellow-400"
                    : "text-green-400"
              }`}
            >
              {asset.risk}
            </p>

            <p className="mt-1 text-xs text-gray-500">
              {asset.level} Risk
            </p>
          </div>

          <div className="rounded-2xl border border-gray-800 bg-gray-950 p-6">
            <p className="text-sm text-gray-500">
              24h Volume
            </p>

            <p className="mt-2 text-3xl font-bold">
              {asset.volume}
            </p>
          </div>

          <div className="rounded-2xl border border-gray-800 bg-gray-950 p-6">
            <p className="text-sm text-gray-500">
              Status
            </p>

            <p className="mt-2 text-xl font-bold text-yellow-400">
              {asset.status}
            </p>
          </div>
        </div>

        <div className="mt-10 rounded-2xl border border-gray-800 bg-gray-950 p-6">
          <h2 className="text-xl font-semibold">
            Latest Signal
          </h2>

          <p className="mt-3 text-gray-400">
            {asset.signal}
          </p>
        </div>

        <div className="mt-10">
          <h2 className="text-2xl font-semibold">
            Why this score?
          </h2>

          <p className="mt-1 text-sm text-gray-500">
            Risk score breakdown generated by the detection engine
          </p>

          <div className="mt-5 grid gap-4 md:grid-cols-3">
            <div className="rounded-2xl border border-gray-800 bg-gray-950 p-6">
              <p className="text-sm text-gray-500">
                Volume Anomaly
              </p>

              <p className="mt-2 text-2xl font-bold">
                {asset.metrics.volumeMultiplier}x
              </p>

              <p className="mt-2 text-sm text-green-400">
                +{volumePoints} risk points
              </p>
            </div>

            <div className="rounded-2xl border border-gray-800 bg-gray-950 p-6">
              <p className="text-sm text-gray-500">
                Large Transfer
              </p>

              <p className="mt-2 text-2xl font-bold">
                {asset.metrics.largeTransfer ? "Detected" : "None"}
              </p>

              <p className="mt-2 text-sm text-green-400">
                +{transferPoints} risk points
              </p>
            </div>

            <div className="rounded-2xl border border-gray-800 bg-gray-950 p-6">
              <p className="text-sm text-gray-500">
                Wallet Concentration
              </p>

              <p className="mt-2 text-2xl font-bold">
                {asset.metrics.walletConcentration}%
              </p>

              <p className="mt-2 text-sm text-green-400">
                +{concentrationPoints} risk points
              </p>
            </div>
          </div>
        </div>

        <div className="mt-10">
          <h2 className="text-2xl font-semibold">
            Investigation Timeline
          </h2>

          <p className="mt-1 text-sm text-gray-500">
            Sequence of detected activity
          </p>

          <div className="mt-5 space-y-4">
            {asset.timeline.map((event) => (
              <div
                key={`${event.time}-${event.title}`}
                className="rounded-2xl border border-gray-800 bg-gray-950 p-6"
              >
                <div className="flex gap-6">
                  <p className="min-w-14 text-sm font-semibold text-green-400">
                    {event.time}
                  </p>

                  <div>
                    <h3 className="font-semibold">
                      {event.title}
                    </h3>

                    <p className="mt-2 text-sm text-gray-400">
                      {event.detail}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-10">
          <h2 className="text-2xl font-semibold">
            On-chain Evidence
          </h2>

          <p className="mt-1 text-sm text-gray-500">
            Wallet and transaction signals linked to this case
          </p>

          <div className="mt-5 overflow-hidden rounded-2xl border border-gray-800 bg-gray-950">
            {asset.evidence.map((item) => (
              <div
                key={item.tx}
                className="grid gap-5 border-b border-gray-800 p-6 last:border-b-0 md:grid-cols-4"
              >
                <div>
                  <p className="text-xs text-gray-500">
                    Wallet
                  </p>

                  <p className="mt-1 font-mono text-sm">
                    {item.wallet}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-gray-500">
                    Transaction
                  </p>

                  <p className="mt-1 font-mono text-sm">
                    {item.tx}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-gray-500">
                    Amount
                  </p>

                  <p className="mt-1 font-semibold">
                    {item.amount}
                  </p>
                </div>

                <div>
                  <p className="text-xs text-gray-500">
                    Signal Type
                  </p>

                  <p className="mt-1 text-sm text-green-400">
                    {item.type}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </main>
  );
}